### ISSUE TITLE
await driver.Navigate().GoToUrl(url) throws System.MissingMethodException

### ISSUE THREAD

**Issue by TheFizz** [ToCSharp/AsyncChromeDriver#13]
```
var chromeDrv = new AsyncChromeDriver();
var driver = new WebDriver(chromeDrv);
await driver.Options().Timeouts.SetImplicitWait(TimeSpan.FromSeconds(5));
string url = "https://google.com";
await driver.Navigate().GoToUrl(url);
```

Throws 

System.MissingMethodException: 'Method not found: 'System.String Zu.WebBrowser.BasicTypes.DriverConfig.get_CommandLineArgumets()'.'

Trace:

```
System.MissingMethodException
  HResult=0x80131513
  Message=Method not found: 'System.String Zu.WebBrowser.BasicTypes.DriverConfig.get_CommandLineArgumets()'.
  Source=AsyncChromeDriver
  StackTrace:
   at Zu.Chrome.ChromeProfilesWorker.OpenChromeProfile(ChromeDriverConfig config)
   at Zu.Chrome.AsyncChromeDriver.<>c__DisplayClass113_0.<OpenChromeProfile>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.AsyncChromeDriver.<OpenChromeProfile>d__113.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.AsyncChromeDriver.<Connect>d__109.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.AsyncChromeDriver.<CheckConnected>d__112.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.DriverCore.WebView.<Load>d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.DriverCore.WindowCommands.<GoToUrl>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at FbSeleniumTarget.ScrapeComparator.<ScrapeAsync>d__16.MoveNext() in E:\WorkProjects\FbSeleniumTarget\FbSeleniumTarget\ScrapeComparator.cs:line 66
```

Any way I could resolve this?

**Comment by ToCSharp** [comment]
Hello.
I have no such exception.
Update to latest version. Nuget version 0.5.6 fixed today.
Let me know if it not helps.
You may write
await driver.GoToUrl(url);

**Comment by TheFizz** [comment]
Something new now.

`System.InvalidOperationException: 'Cannot start process because a file name has not been provided.'`

Trace:
```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot start process because a file name has not been provided.
  Source=System
  StackTrace:
   at System.Diagnostics.Process.Start()
   at Zu.Chrome.ChromeProfilesWorker.OpenChromeProfile(ChromeDriverConfig config)
   at Zu.Chrome.AsyncChromeDriver.<>c__DisplayClass113_0.<OpenChromeProfile>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.AsyncChromeDriver.<OpenChromeProfile>d__113.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.AsyncChromeDriver.<Connect>d__109.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.AsyncChromeDriver.<CheckConnected>d__112.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.DriverCore.WebView.<Load>d__13.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Zu.Chrome.DriverCore.WindowCommands.<GoToUrl>d__4.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Zu.AsyncWebDriver.Remote.TaskExt.<TimeoutAfter>d__1.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable.ConfiguredTaskAwaiter.GetResult()
   at Zu.AsyncWebDriver.Remote.WebDriver.<GoToUrl>d__214.MoveNext()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at FbSeleniumTarget.ScrapeComparator.<ScrapeAsync>d__12.MoveNext() in E:\WorkProjects\FbSeleniumTarget\FbSeleniumTarget\ScrapeComparator.cs:line 142

  This exception was originally thrown at this call stack:
    [External Code]
    FbSeleniumTarget.ScrapeComparator.ScrapeAsync() in ScrapeComparator.cs
```

**Comment by ToCSharp** [comment]
Zu.Chrome.ChromeProfilesWorker.ChromeBinaryFileName = path to Chrome exe
Did not find Chrome in standard paths:
https://github.com/ToCSharp/AsyncChromeDriver/blob/74d22010d1beffc2fd4682be2cf716e39ab3fa12/AsyncChromeDriver/ChromeProfilesWorker.cs#L17

**Comment by TheFizz** [comment]
Will try and report)

Btw, the path for me:
![image](https://user-images.githubusercontent.com/37963412/82547939-2e5aed80-9b63-11ea-9202-f6eca0976f5d.png)

**Comment by TheFizz** [comment]
Works now!

For some reason I keep getting "Element is not attached to the document" when trying this:

```
var container = await driver.FindElement(By.XPath("//*[@id='mount_0_0']/div/div/div[3]/div/div/div[1]/div/div[2]/div/div/div/div"));
                var imgs = await container.FindElements(By.TagName("img")); // Exception here
```

Any way I could just wait for x seconds?

**Comment by ToCSharp** [comment]
public Task<ReadOnlyCollection<IWebElement>> FindElementsByXPath(string xpath, int timeoutMs, CancellationToken cancellationToken = default);
 public Task<IWebElement> FindElementByXPath(string xpath, string notElementId, TimeSpan timeout, CancellationToken cancellationToken = default);

FindElementsByXPath has waiting methods

**Comment by TheFizz** [comment]
Awesome, didn't notice for some reason.. Thank you very much!
